### PR TITLE
Get ready for first I-D version

### PR DESCRIPTION
**Pull request by michielbdejong**
In this PR I'll try to go through the remaining text to complete the switch such that the API spec points to the I-D spec instead of the other way around.
It depends on a number of other PRs that need to be merged first. The branch names are:
* `develop`
*  `accessing-the-resource` -> #114
*  `consolidate-scope-and-assumptions-section` -> #115
*  `reduce-external-references` -> #116
*  `discovery-in-internet-draft` -> #122
*  `internet-draft-format` -> this PR

### CODE REVIEW

**Comment by michielbdejong** [comment]
There are still some issues with the rendering but it's mainly working now:
https://author-tools.ietf.org/api/export/41acaacd-67ef-4498-be8c-a8ce1ffd256e/draft-lopresti-open-cloud-mesh.html

I set the authors to @glpatcern, myself, @MahdiBaghbani, and @mickenordin as these are the people who have been working on the Internet-Draft text this week (I prefer not to be first author myself), we can change this in the future, would be nice to also get @smesterheide and maybe also @schiessle and many others to review the text, so we can then change the list of authors accordingly in future versions.

**Comment by michielbdejong** [comment]
[latest render](https://author-tools.ietf.org/api/export/6afbeb6a-f96d-4db3-905d-95018325fc1e/draft-lopresti-open-cloud-mesh.html)

You can now simply upload the readme from this branch to https://author-tools.ietf.org/ and click 'HTML', then 'open in browser'

**Comment by glpatcern** [comment]
I'm not sure I deserve the honor to be the first author here ;-) but it's good to see where we're converging to!

**Review by mickenordin — APPROVED** [review]

**Comment by michielbdejong** [comment]
Oh wait I accidentally merged this into the `discovery-in-internet-draft` branch instead of into the `develop` branch. Merging it there now.

**Pull request merged**
