### PR TITLE
Convert to OpenAPI 3.0

### PR DESCRIPTION
**Pull request by smesterheide**
I used the Swagger Editor to convert the specification to OpenAPI 3.0

### CODE REVIEW

**Comment by smesterheide** [comment]
Here is the preview for this PR using the [redoc](https://github.com/Redocly/redoc) CDN with the latest version (v2.0.0-alpha): https://smesterheide.github.io/OCM-API/docs.html?branch=openapi-3&repo=OCM-API&user=smesterheide

**Comment by michielbdejong** [comment]
Nice! Looking forward to seeing this merged

**Comment by glpatcern** [comment]
Can we please get https://github.com/cs3org/OCM-API/pull/59 merged before this large refactoring?

I intended to also specify what is required vs optional in a more detailed way, but that could be done after this, using the new 3.0 format.

**Comment by smesterheide** [comment]
Sure, I still need to to manually check if everything was converted correctly, hence the draft.

**Comment by glpatcern** [comment]
Closing in favor of #83, given that meanwhile the spec had evolved quite a bit and this PR remained behind. Please reopen if you think we should use part of this.

**Pull request closed without merging**
